name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Setup SonarCloud
        uses: sonarsource/setup-sonarcloud@v1
        with:
          organization: 'abhishekspad'
          token: ${{ secrets.SONAR_TOKEN }}
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: '.'
